trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build and Publish Artifact'
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.html'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

- deployment: DeployToDev
  displayName: 'Deploy to Dev'
  pool:
    vmImage: 'windows-latest'
  environment: 'dev'
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo "Deploying to Dev"
          displayName: 'Run Deployment Script'
